#
# This Docker file defined for deploying development version of server for testing purposes
#

FROM mcr.microsoft.com/dotnet/sdk:5.0.405

WORKDIR /app

EXPOSE 5000

ENV DB_FILE="Data.db"
ENV CON_STR="Data Source=Data.db"

COPY DevSpectorServer.sln .
COPY src src
COPY tests tests

RUN dotnet restore
RUN dotnet build --no-restore

RUN dotnet dev-certs https

RUN dotnet tool install dotnet-ef --global

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dotnet ef migrations --project src/DevSpector.Database --startup-project src/DevSpector.UI add DockerInit
RUN dotnet ef database --project src/DevSpector.Database --startup-project src/DevSpector.UI update

RUN dotnet publish src/DevSpector.UI -c Debug -r linux-x64 -o publish

RUN cp src/DevSpector.UI/${DB_FILE} publish/${DB_FILE}

CMD ASPNETCORE_URLS=http://+:${PORT} && ASPNETCORE_ENVIRONMENT=Development ./publish/DevSpector.UI
