name: Deploy
on:
  push:
    branches:
      - release*
jobs:
  Deploy-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Deploy to heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        usedocker: true
        docker_heroku_process_type: web
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APPNAME_PROD}}
        heroku_email: ${{secrets.MY_EMAIL}}
      env:
        HD_TARGET_ENV: Production
        HD_CON_STR: ${{secrets.DB_PROD_CON_STR}}
