name: Deploy
on:
  push:
    branches:
      - release*
jobs:
  Deploy-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - name: Setup heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        usedocker: true
        docker_heroku_process_type: web
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: devspector
        heroku_email: ruslan.getmail@gmail.com
