name: Deploy
on:
  push:
    branches:
      - dev*
jobs:
  Deploy-test-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - run: git config user.email "donkardon@list.ru" && git config user.name "CIRCULARKA" && git add -A && git commit -m "Updated code"
    - name: Setup heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        branch: dev
        usedocker: true
        docker_heroku_process_type: web
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: dev-devspector
        heroku_email: ruslan.getmail@gmail.com
      env:
        ASPNETCORE_ENVIRONMENT: Development
