name: .NET

on: [ push ]
jobs:
  Build & Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - name: Initialize database
      run: dotnet ef database --project Server/InvMan.Server.Database --startup-project Server/InvMan.Server.UI update --no-build
    - name: Run Server
      run: dotnet run --no-build --no-restore --project Server/InvMan.Server.UI
