name: .NET

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
  run-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Server
      run: dotnet run --project Server/InvMan.Server.UI
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Test SDK
    - run: dotnet test Tests/Tests.Common
    - run: dotnet test Tests/Tests.Server
