name: .NET

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    # - name: Install dotnet tools
    #   run: dotnet tool install dotnet-ef --global
    # - name: Create database migration
    #   run: dotnet ef migrations --project Server/DevSpector.Database --startup-project Server/DevSpector.UI add Init
    # - name: Create database
    #   run: dotnet ef database --project Server/DevSpector.Database --startup-project Server/DevSpector.UI update
    # - name: Run Server
    #   run: dotnet run --no-build --no-restore --project Server/DevSpector.UI
