name: .NET

on: [ push, pull_request ]
jobs:
  build-run-test:
    runs-on: ubuntu-latest
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.DB_PWD }}
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - name: Install dotnet tools
      run: dotnet tool install --global dotnet-ef
    - name: Update Database
      run: dotnet-ef --project Server/InvMan.Server.Database --startup-project Server/InvMan.Server.UI database update --no-build
    - name: Run Server
      run: dotnet run --project Server/InvMan.Server.UI
    - name: Test SDK
      run: dotnet test Tests/Tests.Common
    - name: Test Server
      run: dotnet test Tests/Tests.Server
